// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: build.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Minimized proto file for sourcekit-bazel-bsp.
// Only includes fields actually used by the BSP implementation.
// Original: https://github.com/bazelbuild/bazel/blob/master/src/main/protobuf/build.proto

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// A rule attribute. Only the fields used by the BSP are included.
public struct BlazeQuery_Attribute: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the attribute
  public var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  /// The type of attribute.
  public var type: BlazeQuery_Attribute.Discriminator {
    get {_type ?? .integer}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  /// The value of the attribute has a list of string values.
  public var stringListValue: [String] = []

  /// If type == BOOLEAN, this is the value of the attribute.
  public var booleanValue: Bool {
    get {_booleanValue ?? false}
    set {_booleanValue = newValue}
  }
  /// Returns true if `booleanValue` has been explicitly set.
  public var hasBooleanValue: Bool {self._booleanValue != nil}
  /// Clears the value of `booleanValue`. Subsequent reads from it will return its default value.
  public mutating func clearBooleanValue() {self._booleanValue = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Indicates the type of attribute.
  public enum Discriminator: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case integer = 1
    case string = 2
    case label = 3
    case output = 4
    case stringList = 5
    case labelList = 6
    case outputList = 7
    case distributionSet = 8
    case license = 9
    case stringDict = 10
    case filesetEntryList = 11
    case labelListDict = 12
    case stringListDict = 13
    case boolean = 14
    case tristate = 15
    case integerList = 16
    case unknown = 18
    case labelDictUnary = 19
    case selectorList = 20
    case labelKeyedStringDict = 21
    case deprecatedStringDictUnary = 17

    public init() {
      self = .integer
    }

  }

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _type: BlazeQuery_Attribute.Discriminator? = nil
  fileprivate var _booleanValue: Bool? = nil
}

/// A rule instance (e.g., cc_library foo, java_binary bar).
public struct BlazeQuery_Rule: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the rule (formatted as an absolute label, e.g. //foo/bar:baz).
  public var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  /// The rule class name (e.g., java_library).
  public var ruleClass: String {
    get {_ruleClass ?? String()}
    set {_ruleClass = newValue}
  }
  /// Returns true if `ruleClass` has been explicitly set.
  public var hasRuleClass: Bool {self._ruleClass != nil}
  /// Clears the value of `ruleClass`. Subsequent reads from it will return its default value.
  public mutating func clearRuleClass() {self._ruleClass = nil}

  /// All of the attributes that describe the rule.
  public var attribute: [BlazeQuery_Attribute] = []

  /// All of the inputs to the rule (formatted as absolute labels).
  public var ruleInput: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _ruleClass: String? = nil
}

/// A file that is an input into the build system.
public struct BlazeQuery_SourceFile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The name of the source file (a label).
  public var name: String {
    get {_name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {self._name = nil}

  /// The location of the source file.
  public var location: String {
    get {_location ?? String()}
    set {_location = newValue}
  }
  /// Returns true if `location` has been explicitly set.
  public var hasLocation: Bool {self._location != nil}
  /// Clears the value of `location`. Subsequent reads from it will return its default value.
  public mutating func clearLocation() {self._location = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _name: String? = nil
  fileprivate var _location: String? = nil
}

/// A target from a blaze query execution.
public struct BlazeQuery_Target: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The type of target contained in the message.
  public var type: BlazeQuery_Target.Discriminator {
    get {_type ?? .rule}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  /// If this target represents a rule, the rule is stored here.
  public var rule: BlazeQuery_Rule {
    get {_rule ?? BlazeQuery_Rule()}
    set {_rule = newValue}
  }
  /// Returns true if `rule` has been explicitly set.
  public var hasRule: Bool {self._rule != nil}
  /// Clears the value of `rule`. Subsequent reads from it will return its default value.
  public mutating func clearRule() {self._rule = nil}

  /// A file that is not generated by the build system.
  public var sourceFile: BlazeQuery_SourceFile {
    get {_sourceFile ?? BlazeQuery_SourceFile()}
    set {_sourceFile = newValue}
  }
  /// Returns true if `sourceFile` has been explicitly set.
  public var hasSourceFile: Bool {self._sourceFile != nil}
  /// Clears the value of `sourceFile`. Subsequent reads from it will return its default value.
  public mutating func clearSourceFile() {self._sourceFile = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Discriminator: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
    case rule = 1
    case sourceFile = 2
    case generatedFile = 3
    case packageGroup = 4
    case environmentGroup = 5

    public init() {
      self = .rule
    }

  }

  public init() {}

  fileprivate var _type: BlazeQuery_Target.Discriminator? = nil
  fileprivate var _rule: BlazeQuery_Rule? = nil
  fileprivate var _sourceFile: BlazeQuery_SourceFile? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "blaze_query"

extension BlazeQuery_Attribute: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Attribute"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}type\0\u{4}\u{4}string_list_value\0\u{4}\u{8}boolean_value\0")

  public var isInitialized: Bool {
    if self._name == nil {return false}
    if self._type == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._type) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.stringListValue) }()
      case 14: try { try decoder.decodeSingularBoolField(value: &self._booleanValue) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._type {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    if !self.stringListValue.isEmpty {
      try visitor.visitRepeatedStringField(value: self.stringListValue, fieldNumber: 6)
    }
    try { if let v = self._booleanValue {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 14)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlazeQuery_Attribute, rhs: BlazeQuery_Attribute) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._type != rhs._type {return false}
    if lhs.stringListValue != rhs.stringListValue {return false}
    if lhs._booleanValue != rhs._booleanValue {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlazeQuery_Attribute.Discriminator: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}INTEGER\0\u{1}STRING\0\u{1}LABEL\0\u{1}OUTPUT\0\u{1}STRING_LIST\0\u{1}LABEL_LIST\0\u{1}OUTPUT_LIST\0\u{1}DISTRIBUTION_SET\0\u{1}LICENSE\0\u{1}STRING_DICT\0\u{1}FILESET_ENTRY_LIST\0\u{1}LABEL_LIST_DICT\0\u{1}STRING_LIST_DICT\0\u{1}BOOLEAN\0\u{1}TRISTATE\0\u{1}INTEGER_LIST\0\u{1}DEPRECATED_STRING_DICT_UNARY\0\u{1}UNKNOWN\0\u{1}LABEL_DICT_UNARY\0\u{1}SELECTOR_LIST\0\u{1}LABEL_KEYED_STRING_DICT\0")
}

extension BlazeQuery_Rule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Rule"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}rule_class\0\u{2}\u{2}attribute\0\u{3}rule_input\0")

  public var isInitialized: Bool {
    if self._name == nil {return false}
    if self._ruleClass == nil {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.attribute) {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._ruleClass) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.attribute) }()
      case 5: try { try decoder.decodeRepeatedStringField(value: &self.ruleInput) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._ruleClass {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if !self.attribute.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.attribute, fieldNumber: 4)
    }
    if !self.ruleInput.isEmpty {
      try visitor.visitRepeatedStringField(value: self.ruleInput, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlazeQuery_Rule, rhs: BlazeQuery_Rule) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._ruleClass != rhs._ruleClass {return false}
    if lhs.attribute != rhs.attribute {return false}
    if lhs.ruleInput != rhs.ruleInput {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlazeQuery_SourceFile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SourceFile"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}location\0")

  public var isInitialized: Bool {
    if self._name == nil {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._location) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._location {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlazeQuery_SourceFile, rhs: BlazeQuery_SourceFile) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._location != rhs._location {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlazeQuery_Target: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Target"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}rule\0\u{3}source_file\0")

  public var isInitialized: Bool {
    if self._type == nil {return false}
    if let v = self._rule, !v.isInitialized {return false}
    if let v = self._sourceFile, !v.isInitialized {return false}
    return true
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._type) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._rule) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._sourceFile) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._type {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._rule {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._sourceFile {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: BlazeQuery_Target, rhs: BlazeQuery_Target) -> Bool {
    if lhs._type != rhs._type {return false}
    if lhs._rule != rhs._rule {return false}
    if lhs._sourceFile != rhs._sourceFile {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension BlazeQuery_Target.Discriminator: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}RULE\0\u{1}SOURCE_FILE\0\u{1}GENERATED_FILE\0\u{1}PACKAGE_GROUP\0\u{1}ENVIRONMENT_GROUP\0")
}
